Meetfolio-Project-CodeZ-Team/Backend

build.gradle
- Git Submodule 적용
```
git submodule update --init --recursive
git submodule update --recursive
git submodule update --remote
```
1. 처음 서브모듈 초기화 하기 (1 번 진행)
2. 서브 모듈 업데이트하기 (2번 진행)
3. 개발 하면서 변경이 있으면 3번 진행
> "build.gradle" 에서 1회 실행
-
- close #2
=> Docs: Main Repository와 Submodule 연결하기

Dockerfile
- DockerFile 추가하기
- DockerFile 추가하여 빌드하기
-
- close #
=> Docs: Docker File 추가

.github/workflows/github-actions.yml, Dockerfile
- github-actions 파일 2차 수정
-
-
- close #
=> Docs : github-actions 파일 2차 수정

.github/workflows/github-actions.yml, Dockerfile
- github actions 3차 수정 및 환경 변수 수정
-
-
- close #
=> docs : github actions 3차 수정 및 환경 변수 수정

src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java, src/main/java/com/codez4/meetfolio/domain/authentication/Authentication.java, src/main/java/com/codez4/meetfolio/domain/board/Board.java, src/main/java/com/codez4/meetfolio/domain/comment/Comment.java, src/main/java/com/codez4/meetfolio/domain/common/BaseTimeEntity.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java, src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java, src/main/java/com/codez4/meetfolio/domain/enums/Authority.java, src/main/java/com/codez4/meetfolio/domain/enums/Major.java, src/main/java/com/codez4/meetfolio/domain/enums/Status.java, src/main/java/com/codez4/meetfolio/domain/experience/Experience.java, src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java, src/main/java/com/codez4/meetfolio/domain/like/Like.java, src/main/java/com/codez4/meetfolio/domain/member/Member.java, src/main/java/com/codez4/meetfolio/domain/model/Model.java, src/main/java/com/codez4/meetfolio/domain/payment/Payment.java, src/main/java/com/codez4/meetfolio/domain/point/Point.java
- 엔티티 파일 설계 오류 수정
- @ ColumnDefault의 default 값 작은 따옴표 삽입
- 다대일 관계 테이블 @ JoinColumn 적용
- @ JoinColumn 지연 로딩 적용
- 인덱스 column not null 적용
- BasetTmeEntity column들 not null 적용
- 바보같은 버그들 죄송합니다 😂
- close #10
=> Fix : 엔티티 파일 설계 오류 수정

src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java
- 회원가입 API의 스웨거 설명 추가
-
-
- close #
=> Hotfix: 스웨거 설명 추가

src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
- memberinfo 비로그인 사용자 로직 추가
-
-
- close #
=> Hotfix: memberinfo 비로그인 사용자 로직 추가

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java, src/main/java/com/codez4/meetfolio/domain/board/Board.java, src/main/java/com/codez4/meetfolio/domain/board/EmploymentBoard.java, src/main/java/com/codez4/meetfolio/domain/board/GroupBoard.java, src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java, src/main/java/com/codez4/meetfolio/domain/board/dto/BoardRequest.java, src/main/java/com/codez4/meetfolio/domain/board/dto/BoardResponse.java, src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/repository/EmploymentBoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/repository/GroupBoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/service/BoardCommandService.java, src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java, src/main/java/com/codez4/meetfolio/domain/comment/Comment.java, src/main/java/com/codez4/meetfolio/domain/comment/controller/CommentController.java, src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java, src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java, src/main/java/com/codez4/meetfolio/domain/enums/BoardType.java, src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java, src/main/java/com/codez4/meetfolio/domain/like/Like.java, src/main/java/com/codez4/meetfolio/domain/like/dto/LikeResponse.java, src/main/java/com/codez4/meetfolio/domain/like/repository/LikeRepository.java, src/main/java/com/codez4/meetfolio/domain/member/Member.java, src/main/java/com/codez4/meetfolio/domain/member/controller/AuthController.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java, src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java, src/main/java/com/codez4/meetfolio/global/utils/TimeUtils.java
- 커뮤니티 게시물 CRUD API 구현
- 취업 정보 게시물 생성 API 구현
- 그룹원 모집 게시물 생성 API 구현
- 커뮤니티 게시물 1개 조회 API 구현
- 커뮤니티 게시물 수정 API 구현
- 커뮤니티 게시물 삭제 API 구현
- 대시보드 API null exeption 버그 픽스
- close #45
=> Feat: 커뮤니티 게시물 CRUD API 구현

src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java
- 대시보드 dto 클래스명 수정
- 스웨거 클래스 인식 오류로 인한 클래스명 수정
-
- close #
=> Hotfix: 대시보드 dto 클래스명 수정

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java, src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/codez4/meetfolio/global/response/code/status/ErrorStatus.java, src/main/java/com/codez4/meetfolio/global/utils/RedisUtil.java
- 로그아웃 로직 추가
- 블랙리스트 확인 로직 추가
-
- close #
=> Feat: 로그아웃 로직 추가

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/dto/BoardResponse.java, src/main/java/com/codez4/meetfolio/domain/admin/dto/DatasetResponse.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java, src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/repository/EmploymentBoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/repository/GroupBoardRepository.java, src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java, src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java, src/main/java/com/codez4/meetfolio/domain/enums/BoardType.java, src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/point/Point.java
- 게시물 검색 및 관리자 게시물 삭제 API 추가
- 사용자 검색 API 구현
- 관리자 검색 API 구현 
- 기존 게시물 목록 조회 API에 parameter을 받아 검색하는 로직 추가
- 관리자 게시물 삭제 API 추가
- 장문 데이터를 받는 String Column에 `@Lob` 어노테이션 추가
-
- close #63
=> Feat: 게시물 검색 및 관리자 게시물 삭제 API 추가

src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java, src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java, src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
- 장문을 받는 cloumn 길이 설정 추가
- `@Lob` 어노테이션 삭제, `@Cloumn` 어노테이션에 length 설정
-
- close #
=> Fix: 장문을 받는 cloumn 길이 설정 추가

src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java, src/test/java/com/codez4/meetfolio/MeetfolioApplicationTests.java
- 자기소개서 목록 조회 API 구현
- 자기소개서 목록 조회 API 구현
- 교수님 피드백 이후 타 사용자 자소서 조회 로직 추가 예정
-
- close #
=> Feat: 자기소개서 목록 조회 API 구현

src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
- corsFilter 프론트 포트 추가
-
-
- close #
=> :bug: Fix: corsFilter 프론트 포트 추가

src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
- fix: cors config DNS 주소 수정
- ip 주소는 연결이 잘 되었는데, 도메인 주소의 경우 www가 필요한것 같아 수정해서 테스트 해보려고 합니다.
-
- close #
=> Fix: cors config DNS 주소 수정

src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
- DNS CORS 마지막 수정
- 포트 번호 없이 DNS 수정
-
- close #
=> Fix: DNS CORS 마지막 수정

src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java, src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java, src/main/java/com/codez4/meetfolio/global/jwt/JwtTokenProvider.java
=> Fix: 로그아웃 로직 수정

src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/dataset/repository/DatasetRepository.java, src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
- 대시보드 API 포인트 통계 산출 로직 수정
-
-
- close #
=> Fix: 대시보드 API 로직 수정

src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java, src/main/java/com/codez4/meetfolio/domain/dataset/repository/DatasetRepository.java, src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java, src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java, src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java, src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java, src/main/java/com/codez4/meetfolio/global/annotation/AuthenticationMemberArgumentResolver.java, src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java, src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/codez4/meetfolio/global/jwt/JwtTokenProvider.java
=> Merge : Main Merge 12차

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
- 관리자 회원 검색 API 구현
- 관리자 회원 검색 API 구현
-
- close #
=> Feat: 관리자 회원 검색 API 구현

src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java, src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java, src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java, src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java, src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java, src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
- soft deleted 된 자기소개서 반환 값에서 제거하여 전달
- 자기소개서 세부 정보 조회 및 삭제 시 연관된 엔티티 null exception 해결
-
-
- close #91
=> Fix: Coverletter API 오류 수정

src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java, src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java, src/main/java/com/codez4/meetfolio/domain/payment/service/KakaoPayService.java, src/main/java/com/codez4/meetfolio/domain/point/dto/PointRequest.java, src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java, src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
- 카카오 페이 승인 API 수정
- 카카오 페이 승인 redirect될 시, 토큰 없이 리다이렉트 되어 401 에러 반환
- 이에 인증 인가 없이 카카오 페이 리다이렉트 되도록 로직 수정
-
- close #
=> Fix: 카카오 페이 승인 API 수정

src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java, src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java, src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
- 내가 댓글 단 게시글 목록 조회 -> 내 댓글 목록 조회 API 변경
-
-
- close #
=> Feat: 내가 댓글 단 게시글 목록 조회 -> 내 댓글 목록 조회 API 변경

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/board/service/BoardCommandService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java, src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java, src/main/java/com/codez4/meetfolio/domain/experience/dto/ExperienceResponse.java, src/main/java/com/codez4/meetfolio/domain/experience/service/ExperienceQueryService.java, src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java, src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
- 타 사용자 포트폴리오 조회 API 구현
-
-
- close #
=> Feat: 타 사용자 포트폴리오 조회 API

src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java, src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentCommandService.java, src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
- 카카오 페이 tid 조회 API 구현
- 카카오 페이 결제 approve 요청을 보내는 과정에서 tid가 필요하여 이를 조회하는 API 구현
-
- close #
=> Feat: 카카오 페이 tid 조회 API 구현

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
- 월별로 필터링하는 로직 수정
-
-
- close #
=> Hotfix : 월별 결제 내역 API 버그 수정

src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
- 모델 정보 조회 response 스펙 수정
- Model 엔티티 구조 변경에 따른 response 스펙을 수정 하였습니다.
-
- close #
=> Fix: 모델 정보 조회 response 스펙 수정

src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java, src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java, src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java, src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java, src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java, src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
- AI 솔루션 만족도 저장 API 구현
- AI 솔루션 만족도 저장 API 구현
- feedback 테이블 id column명 변경
-
- close #117
=> Feat: AI 솔루션 만족도 저장 API 구현

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/member/dto/PasswordRequest.java, src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
- 개인 정보 수정 단계에서 필요한 비밀번호 검증 API를 구현했습니다.
- 
-
- close #124
=> Feat: 비밀번호 검증 API 구현

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/dto/DatasetResponse.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/dataset/repository/DatasetRepository.java, src/main/java/com/codez4/meetfolio/domain/model/service/ModelQueryService.java
-  훈련 가능한 데이터 개수, 활성화된 모델 정보 함께 응답
-
-
- close #125
=> Feat: 관리자 - 훈련 데이터셋 조회 API 에서 훈련 가능한 데이터 개수, 활성화된 모델 정보 함께 응답

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
=> Fix: 관리자 게시물 목록 조회 오류 수정

src/main/java/com/codez4/meetfolio/domain/board/Board.java, src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java, src/main/java/com/codez4/meetfolio/domain/like/Like.java, src/main/java/com/codez4/meetfolio/domain/like/service/LikeCommandService.java
- 좋아요, 댓글 카운트 수정
-
-
- close #
=> Fix : 좋아요, 댓글 카운트 수정

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
=> Fix: 관리자 결제 내역 조회 오류 수정

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
=> Merge : Main Merge 27차

src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java, src/main/java/com/codez4/meetfolio/domain/like/controller/LikeController.java, src/main/java/com/codez4/meetfolio/domain/like/dto/LikeResponse.java, src/main/java/com/codez4/meetfolio/domain/like/service/LikeCommandService.java, src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
- 좋아요 갯수 조회 API 구현
- 프론트 요청으로 인하여 두 가지 방식으로 구현하였습니다.
- 1. 좋아요 API 요청 시 좋아요 갯수 같이 반환
- 2. 좋아요 조회 API 구현
-
- close #136
=> Feat: 좋아요 갯수 조회 API 구현

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java, src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
- 관리자 회원 목록 조회 시 탈퇴한 회원 제거
-
-
- close #
=> Hotfix: 관리자 회원 목록 조회 시 탈퇴한 회원 제거 로직 추가

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java, src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
-
- 모델 상세 정보 조회 response에 성능 필드 추가
- 관리자 - 회원 검색/ 결제 내역 조회 API에서 탈퇴 회원 제거 로직 추가
-
- close #
=> Hotfix : 모델 상세 정보 조회/ 탈퇴 회원 제거 로직 

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java, src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java, src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
=> Merge: Main Merge 29차

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
=> Merge: Main Merge 32차

src/main/java/com/codez4/meetfolio/domain/comment/controller/CommentController.java, src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentRequest.java
=> Hotfix: 댓글 수정 request dto 추가

src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java, src/main/java/com/codez4/meetfolio/domain/enums/ProfileEmoji.java, src/main/java/com/codez4/meetfolio/domain/member/Member.java, src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java, src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
- 프로필 이모지 설정 로직 구현
- member 테이블의 profile 속성을 Enum class인 ProfileEmoji로 변경
- 변경에 따른 로직 수정
- 회원가입/ 회원 정보 수정에 profile 설정 로직 추가
-
- close #152
=> Feat: 프로필 이모지 설정 로직 구현

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/enums/VersionStatus.java, src/main/java/com/codez4/meetfolio/domain/model/Model.java, src/main/java/com/codez4/meetfolio/domain/model/repository/ModelRepository.java
- 모델 삭제 시 soft delete 구현
- Model 테이블에 version_status 속성 추가.
- DEPRECATED(삭제 요청), OBSOLETE(삭제 완료)
- 관리자가 모델 삭제 요청 시, null에서 DEPRECATED로 변경
- 개발자가 Flask API를 통해 최종 파일 삭제
- DB의 version_status OBSOLETE로 변경
-
- close #
=> Refactor : 모델 삭제 시 soft delete 구현

src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/point/controller/PointController.java, src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java, src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
- 포인트 적립 내역 조회 API 구현
-
-
- close #168
=> Feat: 포인트 적립 내역 조회 API 구현

src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java, src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
- 서버 이전으로 인한 url 변경
- 기존 서버 주소에서 이전된 서버 주소로 url 변경하였습니다.
-
- close #173
=> Chore: 서버 이전으로 인한 url 변경

src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java, src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java, src/main/java/com/codez4/meetfolio/domain/board/Board.java, src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java, src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java, src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java, src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java, src/main/java/com/codez4/meetfolio/domain/point/controller/PointController.java, src/main/java/com/codez4/meetfolio/domain/point/dto/PointResponse.java, src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java, src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java, src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
- API http method 변경
-
-
- close #
=> Fix: API http method 변경
